-- EXEMPLO 1 - SELECIONANDO TODAS AS LINHAS E COLUNAS DA TABELA --
SELECT *
FROM PEDIDOS;
SELECT*
FROM CLIENTES;
SELECT *
FROM LOCAIS;
SELECT*
FROM PRODUTOS;
-- EXEMPLO 2 LIMITAR - SELECIONAR ALGUMAS COLUNAS NA TABELA--
SELECT* FROM LOCAIS LIMIT 8;
 -- EXEMPLO 3 - COLOCAR EM ORDEM ALFABETICA DENTRO DA CATEGORIA DE MENOR PARA MAIOR --
SELECT* FROM PRODUTOS ORDER BY PRECO_UNIT;

-- TREINO 1 -  --
SELECT NOME
FROM CLIENTES
ORDER BY NOME DESC;

-- TREINO 2 SELECIONAR ALGUMAS COLUNAS DA TABELA --
-- SELECT ID_cliente as ID cliente, Nome AS 'NOME DO CLIENTE', Email AS 'E-MAIL', Data_nascimento AS 'DATA DE NASCIMENTO',
-- FROM Clientes; --
    
-- TREINO 4 - SELECIONAR APENAS 5 PRIMEIRAS LINHAS DA TABELA DE PRODUTOS --
SELECT *
FROM PRODUTOS LIMIT 5;

-- TREINO 5 - SELECIONAR TODAS AS LINHAS DA TABELA DE PRODUTO ORDENADO PELO PRECO --
SELECT *
FROM PRODUTOS
ORDER BY PRECO_UNIT;

-- TREINO 6 - DESCOBRI O NOME DOS GERENTES DAS LOJAS--
SELECT GERENTE
FROM LOJAS;

-- CRIANDO FILTROS --
SELECT ID_produto, Nome_Produto, Preco_Unit
From produtos;

-- EXEMPLO 1 --
SELECT*
FROM PRODUTOS
WHERE PRECO_UNIT >= 1800;

-- EXEMPLO 2 MOSTRAR APENAS OS PRODUTOS COM PRECOS IGUAIS A R$ 3100 --
SELECT*
FROM PRODUTOS
WHERE PRECO_UNIT = 3100;

-- EXEMPLO 3 MOSTRAR PRODUTOS DA MARCA DELL--
SELECT*
FROM PRODUTOS
WHERE MARCA_PRODUTO = 'DELL';

-- EXEMPLO 4 MOSTRA APENAS PEDIDOS FEITOS NO DIA 3/1/2019 --
SELECT*
FROM PEDIDOS
WHERE DATA_VENDA = '2019-01-03';

-- EXEMPLO 4A  --

SELECT*
FROM PEDIDOS
WHERE DATA_VENDA = '2019-01-03' AND ID_CLIENTE = '33';

-- EXEMPLO 5 MOSTRAR APENAS CLIENTES SOLTEIROS SO SEXO MASCULINO --
SELECT*
FROM CLIENTES
WHERE ESTADO_CIVIL = 'S' AND SEXO = 'M'; 

-- EXEMPLO 6 MOSTRAR PRODUTOS DA MARCA DELL OU SAMSUNG --
SELECT 
    *
FROM
    PRODUTOS
WHERE
    MARCA_PRODUTO IN ('DELL' , 'SAMSUNG')
        AND ID_CATEGORIA = '6';
