-- EXEMPLO 1 - SELECIONANDO TODAS AS LINHAS E COLUNAS DA TABELA --
SELECT *
FROM PEDIDOS;
SELECT*
FROM CLIENTES;
SELECT *
FROM LOCAIS;
SELECT*
FROM PRODUTOS;
-- EXEMPLO 2 LIMITAR - SELECIONAR ALGUMAS COLUNAS NA TABELA--
SELECT* FROM LOCAIS LIMIT 8;
 -- EXEMPLO 3 - COLOCAR EM ORDEM ALFABETICA DENTRO DA CATEGORIA DE MENOR PARA MAIOR --
SELECT* FROM PRODUTOS ORDER BY PRECO_UNIT;

-- TREINO 1 -  --
SELECT NOME
FROM CLIENTES
ORDER BY NOME DESC;

-- TREINO 2 SELECIONAR ALGUMAS COLUNAS DA TABELA --
-- SELECT ID_cliente as ID cliente, Nome AS 'NOME DO CLIENTE', Email AS 'E-MAIL', Data_nascimento AS 'DATA DE NASCIMENTO',
-- FROM Clientes; --
    
-- TREINO 4 - SELECIONAR APENAS 5 PRIMEIRAS LINHAS DA TABELA DE PRODUTOS --
SELECT *
FROM PRODUTOS LIMIT 5;

-- TREINO 5 - SELECIONAR TODAS AS LINHAS DA TABELA DE PRODUTO ORDENADO PELO PRECO --
SELECT *
FROM PRODUTOS
ORDER BY PRECO_UNIT;

-- TREINO 6 - DESCOBRI O NOME DOS GERENTES DAS LOJAS--
SELECT GERENTE
FROM LOJAS;

